spring:
  sql:
    init:
      enabled: true
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    # url:jdbc:h2:~/test
    #    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  #    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true